### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by J5lx** [chobie/php-sundown#42]
It would be nice if php-sundown supported PHP7 (currently the build fails due to API breaks).

**Comment by acasademont** [comment]
+1 here!

**Comment by j5lx** [comment]
@chobie, are you going to work on this extension ever again given the fact that your last activity in this repo was almost two years ago? Because if not I'd like to try to do this myself (even though I barely know C ATM).

**Update 2015-12-17:** I sent chobie an email regarding the issue. Let's hope for a response!

**Comment by pkruithof** [comment]
@J5lx Any luck?

**Comment by j5lx** [comment]
Yep, I just totally forgot to forward it. He replied that he is unable to work on the port himself before March 2016 for personal reasons, but he does plan on updating it himself after updating the protobuf extension, so any patches should be sent before March.

That being said, I'm not entirely sure whether I understood him correctly. However, when I asked him whether I got anything wrong, he didn't reply, so I guess there's nothing fundamentally wrong with my understanding.

**Comment by acasademont** [comment]
we'll have to wait then!

**Comment by aleemb** [comment]
@J5lx @chobie any update on this?

**Comment by j5lx** [comment]
At least not on my side, I'm afraid.

**Comment by aleemb** [comment]
pinging @chobie -- hope all is well. Any hope on your end on this?

**Comment by liuchuang2007** [comment]
looking forward
